export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';
export const AUTHENTICATE_LOGOUT = 'AUTHENTICATE_LOGOUT';

export const GET_QUOTE_DATA = 'GET_QUOTE_DATA';